config/routes.rb
Rails.application.routes.draw do

  resources :workshop_photos
  resources :workshops
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
    :passwords =>"users/passwords"}, :path_names=> { 
      :sign_in => 'login',
      :password => 'forgot', 
      :confirmation => 'confirm', 
      :unlock => 'unblock', 
      :sign_up => 'register', 
      :sign_out => 'signout'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  

  scope "/:locale" do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :about do 
      collection do
        get 'map'
      end
    end
    resources :posts, :only =>[:index, :show]
    resources :articles, :only =>[:index, :show]
    resources :howtos, :only =>[:index, :show]
    resources :activities, :only =>[:index, :show]
    resources :projects, :only =>[ :show]
    resources :therapists, :only =>[:index, :show]
    resources :home
    get 'home/index'
    root 'home#index'
    
  end
  root 'home#index'
 end

app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :author
  belongs_to :category
  has_many :pictures, :class_name => "Ckeditor::Picture", :as => "assetable"

end

app/controllers/workshops_controller.rb
class WorkshopsController < InheritedResources::Base

  private

    def workshop_params
      params.require(:workshop).permit(:title, :desctiption, :slung, :meta_description, :meta_keyworlds, :meta_title, :start, :finish, :capacity, :teacher_id, :available_on, :discontinue_on, :category_id, :price, :cost)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= simple_form_for(@workshop) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :desctiption %>
    <%= f.input :slung %>
    <%= f.input :meta_description %>
    <%= f.input :meta_keyworlds %>
    <%= f.input :meta_title %>
    <%= f.input :start %>
    <%= f.input :finish %>
    <%= f.input :capacity %>
    <%= f.association :teacher %>
    <%= f.input :available_on %>
    <%= f.input :discontinue_on %>
    <%= f.association :category %>
    <%= f.input :price %>
    <%= f.input :cost %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<h1>Editing Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workshops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desctiption</th>
      <th>Slung</th>
      <th>Meta description</th>
      <th>Meta keyworlds</th>
      <th>Meta title</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Capacity</th>
      <th>Teacher</th>
      <th>Available on</th>
      <th>Discontinue on</th>
      <th>Category</th>
      <th>Price</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.title %></td>
        <td><%= workshop.desctiption %></td>
        <td><%= workshop.slung %></td>
        <td><%= workshop.meta_description %></td>
        <td><%= workshop.meta_keyworlds %></td>
        <td><%= workshop.meta_title %></td>
        <td><%= workshop.start %></td>
        <td><%= workshop.finish %></td>
        <td><%= workshop.capacity %></td>
        <td><%= workshop.teacher %></td>
        <td><%= workshop.available_on %></td>
        <td><%= workshop.discontinue_on %></td>
        <td><%= workshop.category %></td>
        <td><%= workshop.price %></td>
        <td><%= workshop.cost %></td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

app/views/workshops/new.html.erb
<h1>New Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @workshop.title %>
</p>

<p>
  <strong>Desctiption:</strong>
  <%= @workshop.desctiption %>
</p>

<p>
  <strong>Slung:</strong>
  <%= @workshop.slung %>
</p>

<p>
  <strong>Meta description:</strong>
  <%= @workshop.meta_description %>
</p>

<p>
  <strong>Meta keyworlds:</strong>
  <%= @workshop.meta_keyworlds %>
</p>

<p>
  <strong>Meta title:</strong>
  <%= @workshop.meta_title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @workshop.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @workshop.finish %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @workshop.capacity %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @workshop.teacher %>
</p>

<p>
  <strong>Available on:</strong>
  <%= @workshop.available_on %>
</p>

<p>
  <strong>Discontinue on:</strong>
  <%= @workshop.discontinue_on %>
</p>

<p>
  <strong>Category:</strong>
  <%= @workshop.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @workshop.price %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @workshop.cost %>
</p>

<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %>