config/routes.rb
Rails.application.routes.draw do

  resources :workshop_photos
  resources :workshops
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
    :passwords =>"users/passwords"}, :path_names=> { 
      :sign_in => 'login',
      :password => 'forgot', 
      :confirmation => 'confirm', 
      :unlock => 'unblock', 
      :sign_up => 'register', 
      :sign_out => 'signout'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  

  scope "/:locale" do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :about do 
      collection do
        get 'map'
      end
    end
    resources :posts, :only =>[:index, :show]
    resources :articles, :only =>[:index, :show]
    resources :howtos, :only =>[:index, :show]
    resources :activities, :only =>[:index, :show]
    resources :projects, :only =>[ :show]
    resources :therapists, :only =>[:index, :show]
    resources :home
    get 'home/index'
    root 'home#index'
    
  end
  root 'home#index'
 end

app/models/workshop_photo.rb
class WorkshopPhoto < ApplicationRecord
  belongs_to :workshop
end

app/controllers/workshop_photos_controller.rb
class WorkshopPhotosController < InheritedResources::Base

  private

    def workshop_photo_params
      params.require(:workshop_photo).permit(:workshop_id, :photo)
    end
end

app/helpers/workshop_photos_helper.rb
module WorkshopPhotosHelper
end

app/views/workshop_photos/_form.html.erb
<%= simple_form_for(@workshop_photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :workshop %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/workshop_photos/edit.html.erb
<h1>Editing Workshop Photo</h1>

<%= render 'form', workshop_photo: @workshop_photo %>

<%= link_to 'Show', @workshop_photo %> |
<%= link_to 'Back', workshop_photos_path %>

app/views/workshop_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workshop Photos</h1>

<table>
  <thead>
    <tr>
      <th>Workshop</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshop_photos.each do |workshop_photo| %>
      <tr>
        <td><%= workshop_photo.workshop %></td>
        <td><%= workshop_photo.photo %></td>
        <td><%= link_to 'Show', workshop_photo %></td>
        <td><%= link_to 'Edit', edit_workshop_photo_path(workshop_photo) %></td>
        <td><%= link_to 'Destroy', workshop_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop Photo', new_workshop_photo_path %>

app/views/workshop_photos/new.html.erb
<h1>New Workshop Photo</h1>

<%= render 'form', workshop_photo: @workshop_photo %>

<%= link_to 'Back', workshop_photos_path %>

app/views/workshop_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workshop:</strong>
  <%= @workshop_photo.workshop %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @workshop_photo.photo %>
</p>

<%= link_to 'Edit', edit_workshop_photo_path(@workshop_photo) %> |
<%= link_to 'Back', workshop_photos_path %>