config/routes.rb
Rails.application.routes.draw do

  resources :workshop_photos
  resources :workshops
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
    :passwords =>"users/passwords"}, :path_names=> { 
      :sign_in => 'login',
      :password => 'forgot', 
      :confirmation => 'confirm', 
      :unlock => 'unblock', 
      :sign_up => 'register', 
      :sign_out => 'signout'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  

  scope "/:locale" do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :about do 
      collection do
        get 'map'
      end
    end
    resources :posts, :only =>[:index, :show]
    resources :articles, :only =>[:index, :show]
    resources :howtos, :only =>[:index, :show]
    resources :activities, :only =>[:index, :show]
    resources :projects, :only =>[ :show]
    resources :therapists, :only =>[:index, :show]
    resources :home
    get 'home/index'
    root 'home#index'
    
  end
  root 'home#index'
 end

app/views/share/footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Contact -->
        <section class="contact">
          <header>
            <h3><%=t('footer.joinus')%></h3>
          </header>
          <ul class="icons">
            <li><a target="_blank" href="https://www.facebook.com/ArtbyHeartBangkok/" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><%= link_to "",map_about_index_path,data: { modal: true},:class=>"icon fa-map-marker " %>
            </li>
          </ul>
        </section>

        <!-- Copyright -->
        <div class="copyright">
          <ul class="menu">
            <li>&copy; Art by Heart Bangkok. All rights reserved.</li>
            <li>Developed by: <a href="mailto:pattiyaa@gmail.com">Pattiya Akaratawee</a></li>
          </ul>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/share/header.html.erb
<% if user_signed_in? && !current_user.blank? %>

Hi <%= current_user.name %>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to  new_user_session_path ,data: { modal: true} do%>
	<i class="fa fa-user"></i><span>SIGN IN</span>
<%end%>
<% end %>

app/views/share/locale.html.erb
<div class="locale">
	<ul class="menu">
		<%=locale_link "ไทย",url_for( :locale => 'th' ),:th%>
		<%=locale_link "english",url_for( :locale => 'en' ),:en%>
	</ul>
</div>

app/views/share/menu.html.erb
<nav id="nav">
  <ul>
    <%= nav_link t(:menu_home),root_path %>
    <%= nav_link t(:menu_article),articles_path %>
    <%= nav_link t(:menu_howto),howtos_path%>
    <%= nav_link t(:menu_activities),activities_path %>
  <!--   <%= nav_link t(:menu_schedual),"#" %> -->
    <%= nav_link t(:menu_therapist), root_path + '/#Therapist'%>
  <!--   <%= nav_link t(:menu_products),"#" %> -->
    <%= nav_link t(:menu_aboutus),about_index_path %>
    <li><%= render template: "/share/signin"%></li>
  </ul>
</nav>

app/views/share/signin.html.erb
<% if user_signed_in? && !current_user.blank? %>
<div class="image fit profile">
<%= image_tag  current_user.image, :class=>"mini" %>
</div>
<span> <p><%= t(:hi)%>	<%=  current_user.name %></p></span>
<%= link_to t(:signout), destroy_user_session_path, :method => :destroy %>
<% else %>
<%= link_to  new_user_session_path ,data: { modal: true} do%>
	<i class="fa fa-user"></i>&nbsp<span class="text-uppercase"><%=t(:signin)%></span>
<%end%>
<% end %>