config/routes.rb
Rails.application.routes.draw do

  resources :workshop_photos
  resources :workshops
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
    :passwords =>"users/passwords"}, :path_names=> { 
      :sign_in => 'login',
      :password => 'forgot', 
      :confirmation => 'confirm', 
      :unlock => 'unblock', 
      :sign_up => 'register', 
      :sign_out => 'signout'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  

  scope "/:locale" do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :about do 
      collection do
        get 'map'
      end
    end
    resources :posts, :only =>[:index, :show]
    resources :articles, :only =>[:index, :show]
    resources :howtos, :only =>[:index, :show]
    resources :activities, :only =>[:index, :show]
    resources :projects, :only =>[ :show]
    resources :therapists, :only =>[:index, :show]
    resources :home
    get 'home/index'
    root 'home#index'
    
  end
  root 'home#index'
 end

app/models/author.rb
class Author < ApplicationRecord
	attr_accessor :picture
	has_many :projects 
	accepts_nested_attributes_for :projects, :allow_destroy => true
    
	# mount_uploader :avatarimg, CloudinaryImageUploader
	has_one :avatarimg ,:class_name => "Ckeditor::Picture", :as => "assetable"

end

app/views/admin/authors/_index.html.erb
<% @authors.each do |author| %>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-4">
  
    <% if author.avatarimg.present? %>
      <img class="img-thumbnail" src=<%= author.avatarimg.url%> />
      <%end%>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-8">
    <div><h4><%= author.name%></h4></div>
    <div><p ><%= author.title%></p></div>
     <div><p ><%= author.subtitle%></p></div>
  </div>
</div>
<%end%>
<div class="card-columns">
<div class="card-deck-wrapper">
  <div class="card-deck">
  <% @authors.each do |author| %>
   
    <div class="card">
      <% if author.avatarimg.present? %>
      <img class="card-img-top" src=<%= author.avatarimg.url%> style="width:100%">
      <%end%>
      <div class="card-block">
        <h4 class="card-title"><%= author.name%></h4>
        <p class="card-text"><%= author.title%></p>
      </div>
      <div class="card-block pull-right">
        <%= link_to edit_admin_author_path(author) do %>
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <% end %>
        <%= link_to admin_author_path(author), method: :delete, data: { confirm: 'Are you sure?' }  do %>
        <i class="fa fa fa-eraser" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  
  <%end%>
</div>
</div>
</div>

app/views/admin/authors/_profile.html.erb
<div class="wrap_head">
  <h2><%=author.name%></h2>
</div>
<div class="wrap_content row">
  <div class="col-xs-12 col-sm-8 col-lg-8">
    <div>
      <h3><%=author.title%></h3>
      <p><%=author.subtitle%></p>
    </div>
    <h3><%= t('therapist.profile')%></h3>
    <p><%=  author.profile.present? ? author.profile.html_safe : ''%></p>
  </div>
  <div class="col-xs-12 col-sm-4 col-lg-4">
    <div class="image fit"><img class="img-border-r8" src=<%=author.avatarimg.url if author.avatarimg.present? %> ></div>
  </div>
</div>

app/views/admin/authors/_show.html.erb
<%= render "profile" , author: @author%> 

<section>
  <header>
   <%= link_to admin_author_projects_path(:author_id => @author.id) do %>
        <h4><%= t('therapist.portfolio')%></h4>
   <%end%>
 </header>
 <div class="card-deck-wrapper">
   <div class="card-deck">
    <% @author.projects.each_with_index do |project,index| %>
    <div class="card card-inverse text-xs-center">
      <div class="image fit hight350"> 
        <%= carousel_for(project.pictures.map{|p| p.url}) %>
      </div>
      <div class="card-img-overlay">
        <h4 class="card-title"><%= project.title%></h4>
        <p class="card-text"><%= project.description.html_safe%></p>
        <hr class="card-title"/>
        <h4 class="card-title"><%= link_to t(:edit), edit_admin_author_project_path(:author_id => project.author_id, :id => project.id)%></h4>
      </div>
    </div> 
    <%end%>
  </div>
</div>
</section>

app/views/admin/authors/projects.html.erb
<% if @projects.blank? %>
<p><%=  t(:ntf_projects)%></p>
<% else %>
<% @projects.each do |project| %>
<div class="card">
	<div class="card-block">
	<h4 class="card-title"><%=project.title%></h4>
		<h6 class="card-subtitle text-muted"><%=project.description%></h6>
	</div>
	<img src=<%= project.pictures.first.url%> alt="Card image"  style="width:100%">
	<div class="card-block pull-right">
		<%= link_to edit_admin_project_path(project) do %>
        	<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <% end %>
        <%= link_to admin_project_path(project), method: :destroy, data: { confirm: 'Are you sure?' }  do %>
        	<i class="fa fa fa-eraser" aria-hidden="true"></i>
  		<% end %>
	</div>
</div>
<%end%>
<% end %>